# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.2
    container_name: netology_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./dump:/var/dump