---
# tasks file for apache-deploy
- name: Install Apache web server
  package:
    name: apache2
    state: present

- name: Configure index.html file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart apache